apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "jks.kemo.dev/v1alpha1",
          "kind": "ClusterJavaKeystore",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "jks-operator"
            },
            "name": "clusterjavakeystore-sample"
          },
          "spec": {
            "rootCAConfigMaps": [
              {
                "name": "root-trusted-ca",
                "namespace": "default"
              }
            ]
          }
        },
        {
          "apiVersion": "jks.kemo.dev/v1alpha1",
          "kind": "JavaKeystore",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "jks-operator"
            },
            "name": "javakeystore-sample",
            "namespace": "default"
          },
          "spec": {
            "rootCAConfigMaps": [
              {
                "key": "ca.crt",
                "name": "javakeystore-sample-ca"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-05-02T14:10:44Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: jks-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterJavaKeystore is the Schema for the clusterjavakeystores
        API.
      displayName: Cluster Java Keystore
      kind: ClusterJavaKeystore
      name: clusterjavakeystores.jks.kemo.dev
      version: v1alpha1
    - description: JavaKeystore is the Schema for the javakeystores API.
      displayName: Java Keystore
      kind: JavaKeystore
      name: javakeystores.jks.kemo.dev
      version: v1alpha1
  description: Generates Java Keystores dynamically for distribution to Java-based
    applications
  displayName: Java Keystore Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - jks.kemo.dev
          resources:
          - clusterjavakeystores
          - javakeystores
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - jks.kemo.dev
          resources:
          - clusterjavakeystores/finalizers
          - javakeystores/finalizers
          verbs:
          - update
        - apiGroups:
          - jks.kemo.dev
          resources:
          - clusterjavakeystores/status
          - javakeystores/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: jks-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: jks-operator
          control-plane: controller-manager
        name: jks-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: jks-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: jks-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: jks-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: jks-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - jks
  - java
  - keystore
  - certificate
  - ca
  - root
  links:
  - name: Jks Operator
    url: https://jks-operator.domain
  maintainers:
  - email: ken@kenmoini.com
    name: Ken Moini
  maturity: alpha
  provider:
    name: Ken Moini
    url: https://github.com/kenmoini/jks-operator
  version: 0.0.1
