apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jks-operator
  name: jks-operator-clusterjavakeystore-admin-role
rules:
- apiGroups:
  - jks.kemo.dev
  resources:
  - clusterjavakeystores
  verbs:
  - '*'
- apiGroups:
  - jks.kemo.dev
  resources:
  - clusterjavakeystores/status
  verbs:
  - get
