---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jks.kemo.dev
  resources:
  - clusterjavakeystores
  - javakeystores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jks.kemo.dev
  resources:
  - clusterjavakeystores/finalizers
  - javakeystores/finalizers
  verbs:
  - update
- apiGroups:
  - jks.kemo.dev
  resources:
  - clusterjavakeystores/status
  - javakeystores/status
  verbs:
  - get
  - patch
  - update
