apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    categories: |
      Developer Tools,Integration & Delivery,Middleware,OpenShift Optional,Security
    certified: "false"
    containerImage: quay.io/kenmoini/jks-operator:latest
    description: Generates Java Keystores dynamically for distribution to Java-based
      applications
    displayName: Java Keystore Operator
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    operatorframework.io/suggested-namespace: jks-operator
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/os.zos: supported
  name: jks-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterJavaKeystore is the Schema for the clusterjavakeystores
        API.
      displayName: Cluster Java Keystore
      kind: ClusterJavaKeystore
      name: clusterjavakeystores.jks.kemo.dev
      version: v1alpha1
    - description: JavaKeystore is the Schema for the javakeystores API.
      displayName: Java Keystore
      kind: JavaKeystore
      name: javakeystores.jks.kemo.dev
      version: v1alpha1
  description: Generates Java Keystores dynamically for distribution to Java-based
    applications
  displayName: Java Keystore Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - jks
  - java
  - keystore
  - certificate
  - ca
  - root
  - tls
  links:
  - name: Java Keystore Operator
    url: https://github.com/kenmoini/jks-operator
  maintainers:
  - email: ken@kenmoini.com
    name: Ken Moini
  maturity: alpha
  minKubeVersion: 1.21.0
  provider:
    name: Ken Moini
    url: https://github.com/kenmoini/jks-operator
  relatedImages:
  - image: quay.io/kenmoini/jks-operator:v0.0.0
    name: jks-operator
  version: 0.0.0
