---
apiVersion: jks.kemo.dev/v1alpha1
kind: ClusterJavaKeystore
metadata:
  labels:
    app.kubernetes.io/name: jks-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterjavakeystore-sample
spec:
  # addDefaultCACertificates is an optional boolean that indicates if the default CA certificates in
  # the controller container should be included in the generated Java Keystore. Default is false.
  addDefaultCACertificates: true
  
  # defaultCACertificatesPath s the path to the default CA certificates file - in the UBI container it is at /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem.
  # This field is optional and typically only used when the controller is running in a non-UBI container or externally.
  # defaultCACertificatesPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

  # rootCAConfigMaps is a list of ConfigMaps that contain Root CA certificates in PEM format.
  # The operator watches for changes to these ConfigMaps and updates the generated Java Keystore accordingly.
  # Each ConfigMap must have a key that contains the Root CA certificate(s) in PEM format. 
  # If a key is not specified, the operator will enumerate all the keys to find any certificates.
  # rootCAConfigMaps:
  #   - name: root-trusted-ca
  #     namespace: default

  # keyStorePasswordSecretRef is optional - when set, the operator will use the specified Secret as the password source for the generated Java Keystore instead of generating a random password.
  # The Secret must have a key that contains the password as a string, default key is 'password'.
  # If a key is not specified, the operator will use the default key `changeit`.
  # keyStorePasswordSecretRef:
  #   name: my-keystore-password
  #   key: password

  # namespaceSelector is an optional label selector to restrict the namespaces that the operator watches for referenced ConfigMaps and Secrets. If not set, the operator watches all namespaces.
  # namespaceSelector:
  #   matchLabels:
  #     jks.kemo.dev/clusterkeystore: clusterjavakeystore-sample
  #   matchExpressions:
  #     - key: jks.kemo.dev/clusterkeystore
  #       operator: In
  #       values:
  #         - clusterjavakeystore-sample

  # systemNamespace is the namespace the operator is running in and where the Java Keystore ConfigMap and Secret will be created.
  # If left absent, it will default to "jks-operator".
  # systemNamespace: jks-operator