//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterJavaKeystore) DeepCopyInto(out *ClusterJavaKeystore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterJavaKeystore.
func (in *ClusterJavaKeystore) DeepCopy() *ClusterJavaKeystore {
	if in == nil {
		return nil
	}
	out := new(ClusterJavaKeystore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterJavaKeystore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterJavaKeystoreList) DeepCopyInto(out *ClusterJavaKeystoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterJavaKeystore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterJavaKeystoreList.
func (in *ClusterJavaKeystoreList) DeepCopy() *ClusterJavaKeystoreList {
	if in == nil {
		return nil
	}
	out := new(ClusterJavaKeystoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterJavaKeystoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterJavaKeystoreSpec) DeepCopyInto(out *ClusterJavaKeystoreSpec) {
	*out = *in
	if in.RootCAConfigMaps != nil {
		in, out := &in.RootCAConfigMaps, &out.RootCAConfigMaps
		*out = make([]ConfigMapReference, len(*in))
		copy(*out, *in)
	}
	out.KeyStorePasswordSecretRef = in.KeyStorePasswordSecretRef
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.TargetConfigMap = in.TargetConfigMap
	out.TargetSecret = in.TargetSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterJavaKeystoreSpec.
func (in *ClusterJavaKeystoreSpec) DeepCopy() *ClusterJavaKeystoreSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterJavaKeystoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterJavaKeystoreStatus) DeepCopyInto(out *ClusterJavaKeystoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterJavaKeystoreStatus.
func (in *ClusterJavaKeystoreStatus) DeepCopy() *ClusterJavaKeystoreStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterJavaKeystoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapReference) DeepCopyInto(out *ConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapReference.
func (in *ConfigMapReference) DeepCopy() *ConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaKeystore) DeepCopyInto(out *JavaKeystore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaKeystore.
func (in *JavaKeystore) DeepCopy() *JavaKeystore {
	if in == nil {
		return nil
	}
	out := new(JavaKeystore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaKeystore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaKeystoreList) DeepCopyInto(out *JavaKeystoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JavaKeystore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaKeystoreList.
func (in *JavaKeystoreList) DeepCopy() *JavaKeystoreList {
	if in == nil {
		return nil
	}
	out := new(JavaKeystoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaKeystoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaKeystoreSpec) DeepCopyInto(out *JavaKeystoreSpec) {
	*out = *in
	if in.RootCAConfigMaps != nil {
		in, out := &in.RootCAConfigMaps, &out.RootCAConfigMaps
		*out = make([]NamespacedConfigMapReference, len(*in))
		copy(*out, *in)
	}
	out.KeyStorePasswordSecretRef = in.KeyStorePasswordSecretRef
	if in.TLSCertSecretRef != nil {
		in, out := &in.TLSCertSecretRef, &out.TLSCertSecretRef
		*out = make([]NamespacedSecretReference, len(*in))
		copy(*out, *in)
	}
	out.TargetConfigMap = in.TargetConfigMap
	out.TargetSecret = in.TargetSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaKeystoreSpec.
func (in *JavaKeystoreSpec) DeepCopy() *JavaKeystoreSpec {
	if in == nil {
		return nil
	}
	out := new(JavaKeystoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaKeystoreStatus) DeepCopyInto(out *JavaKeystoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaKeystoreStatus.
func (in *JavaKeystoreStatus) DeepCopy() *JavaKeystoreStatus {
	if in == nil {
		return nil
	}
	out := new(JavaKeystoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedConfigMapReference) DeepCopyInto(out *NamespacedConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedConfigMapReference.
func (in *NamespacedConfigMapReference) DeepCopy() *NamespacedConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretReference) DeepCopyInto(out *NamespacedSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretReference.
func (in *NamespacedSecretReference) DeepCopy() *NamespacedSecretReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
